using CsIndex.Core.Analysis;
using CsIndex.Core.Caching;
using CsIndex.Core.Input;
using CsIndex.Core.Model;
using CsIndex.Storage;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace CsIndex.IntegrationTests;

public sealed class CompilationOnlyGeneratedDocumentPersistenceTests
{
    [Fact]
    public async Task AnalyzeAndSave_CompilationOnlyDependencyEndpointIsPersistable()
    {
        const string indexedSource = """
            namespace App;
            public sealed class Consumer
            {
                public int Run() => GeneratedApi.Helper.Value();
            }
            """;
        const string generatedSource = """
            // <auto-generated/>
            namespace GeneratedApi;
            public static class Helper
            {
                public static int Value() => Hidden();
                private static int Hidden() => 42;
            }
            """;

        var cancellationToken = TestContext.Current.CancellationToken;
        var root = Path.Combine(
            Path.GetTempPath(),
            "csindex-compilation-only-persistence-tests",
            Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        try
        {
            var projectPath = WriteFile(root, @"Game\Game.csproj", "<Project />");
            var indexedPath = WriteFile(root, @"Game\Main.cs", indexedSource);
            var generatedPath = CreateDifferentDrivePath(
                root,
                @"packages\generator\Helper.generated.cs");
            var loaded = CreateLoadedWorkspace(
                projectPath,
                (indexedPath, "Main.cs", indexedSource),
                (generatedPath, "Helper.cs", generatedSource));
            var input = new ResolvedInput(InputMode.Project, projectPath, root, [projectPath]);
            var options = new IndexOptions { InputPath = projectPath, ForcedMode = InputMode.Project };
            var coordinator = AnalysisCoordinator.CreateForTesting((_, _, _) => Task.FromResult(loaded));
            var paths = IndexPathResolver.CreateForIndex(
                Path.Combine(root, ".csindex", "index.sqlite"),
                root);

            using var prepared = await coordinator.PrepareAsync(
                input,
                options,
                paths,
                cancellationToken);
            var result = await coordinator.AnalyzeAsync(
                prepared,
                options,
                [],
                [],
                cancellationToken);
            var snapshot = result.Snapshot;
            var value = Assert.Single(snapshot.Symbols.Values, symbol => symbol.Name == "Value");
            var helper = Assert.Single(snapshot.Symbols.Values, symbol => symbol.Name == "Helper");
            Assert.Null(value.PreferredDeclarationKey);
            Assert.Null(value.SourceDocumentKey);
            Assert.Equal(1, snapshot.DocumentsExcluded);
            Assert.Single(
                snapshot.Warnings,
                warning => warning.Contains(
                    "Helper.generated.cs",
                    StringComparison.OrdinalIgnoreCase));
            Assert.DoesNotContain(snapshot.Symbols.Values, symbol => symbol.Name == "Hidden");
            Assert.DoesNotContain(snapshot.Documents, document =>
                document.NormalizedPath.Contains("Helper.generated.cs", StringComparison.OrdinalIgnoreCase));
            Assert.DoesNotContain(snapshot.Declarations.Values, declaration =>
                declaration.DocumentKey.Contains("Helper.generated.cs", StringComparison.OrdinalIgnoreCase));
            Assert.DoesNotContain(snapshot.Calls, call => call.CallerSymbolKey == value.StableKey);

            var index = new SqliteIndex(Path.Combine(root, "index.sqlite"));
            await index.SaveAsync(snapshot, cancellationToken);
            Assert.Null(value.ProjectKey);
            Assert.Null(helper.ProjectKey);

            var repository = index.CreateQueryRepository();
            var profile = await repository.GetProfileAsync(snapshot.Profile.Name, cancellationToken);
            var run = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Run",
                typeSimpleName: "Consumer",
                kind: IndexedSymbolKind.Method,
                sourceOnly: true,
                cancellationToken: cancellationToken));
            var storedValue = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Value",
                typeSimpleName: "Helper",
                kind: IndexedSymbolKind.Method,
                sourceOnly: false,
                cancellationToken: cancellationToken));
            Assert.Null(storedValue.PreferredDeclaration);
            Assert.Null(storedValue.DocumentPath);
            Assert.Empty(await repository.FindDocumentsAsync(
                profile.Id,
                "packages/generator/Helper.generated.cs",
                cancellationToken));
            Assert.Empty(await repository.GetCallsByCallerAsync(
                profile.Id,
                [storedValue.Id],
                GeneratedFilter.Include,
                cancellationToken: cancellationToken));

            var calls = await repository.GetCallsByCallerAsync(
                profile.Id,
                [run.Id],
                GeneratedFilter.Include,
                cancellationToken: cancellationToken);
            var call = Assert.Single(calls);
            Assert.Equal(storedValue.Id, call.CalleeDefinitionId);
            Assert.Equal("Main.cs", call.DocumentPath.Split('/').Last());
        }
        finally
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }
    }

    private static string CreateDifferentDrivePath(string referencePath, string relativePath)
    {
        var currentDrive = char.ToUpperInvariant(Path.GetPathRoot(referencePath)![0]);
        var otherDrive = currentDrive == 'Z' ? 'Y' : 'Z';
        return $"{otherDrive}:\\{relativePath}";
    }

    private static LoadedWorkspace CreateLoadedWorkspace(
        string projectPath,
        params (string Path, string Name, string Source)[] documents)
    {
        var workspace = new AdhocWorkspace();
        var projectId = ProjectId.CreateNewId();
        var metadataReferences = GetPlatformReferences();
        var projectInfo = ProjectInfo.Create(
            projectId,
            VersionStamp.Create(),
            "TestProject",
            "TestProject",
            LanguageNames.CSharp,
            filePath: projectPath,
            outputFilePath: null,
            compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary),
            parseOptions: new CSharpParseOptions(LanguageVersion.Latest),
            metadataReferences: metadataReferences);
        var solution = workspace.CurrentSolution.AddProject(projectInfo);
        foreach (var (path, name, source) in documents)
        {
            solution = solution.AddDocument(
                DocumentInfo.Create(
                    DocumentId.CreateNewId(projectId, name),
                    name,
                    loader: TextLoader.From(
                        TextAndVersion.Create(SourceText.From(source), VersionStamp.Create(), path)),
                    filePath: path));
        }

        Assert.True(workspace.TryApplyChanges(solution));
        var project = workspace.CurrentSolution.GetProject(projectId)!;
        return new LoadedWorkspace(
            workspace,
            [project],
            metadataReferences
                .OfType<PortableExecutableReference>()
                .Select(reference => reference.FilePath!)
                .ToArray(),
            [],
            0);
    }

    private static IReadOnlyList<MetadataReference> GetPlatformReferences() =>
        ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))!
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            .Select(path => MetadataReference.CreateFromFile(path))
            .ToArray();

    private static string WriteFile(string root, string relativePath, string contents)
    {
        var path = Path.Combine(root, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, contents);
        return path;
    }
}
