using CsIndex.Core.Analysis;
using CsIndex.Core.Caching;
using CsIndex.Core.Input;
using CsIndex.Core.Model;
using CsIndex.Storage;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace CsIndex.IntegrationTests;

public sealed class CompilationOnlyGeneratedDocumentPersistenceTests
{
    [Fact]
    public async Task AnalyzeAndSave_CompilationOnlyEndpointsRemainProjectScopedAcrossIdenticalProjects()
    {
        const string generatedSource = """
            // <auto-generated/>
            namespace GeneratedApi;
            public static class Helper
            {
                public static int Value() => 42;
            }
            """;
        const string indexedSourceA = """
            namespace AppA;
            public sealed class ConsumerA
            {
                public int Run() => GeneratedApi.Helper.Value();
            }
            """;
        const string indexedSourceB = """
            namespace AppB;
            public sealed class ConsumerB
            {
                public int Run() => GeneratedApi.Helper.Value();
            }
            """;

        var cancellationToken = TestContext.Current.CancellationToken;
        var root = Path.Combine(
            Path.GetTempPath(),
            "csindex-compilation-only-persistence-tests",
            Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        try
        {
            var projectPathA = WriteFile(root, @"Alpha\Alpha.csproj", "<Project />");
            var projectPathB = WriteFile(root, @"Beta\Beta.csproj", "<Project />");
            var indexedPathA = WriteFile(root, @"Alpha\Main.cs", indexedSourceA);
            var indexedPathB = WriteFile(root, @"Beta\Main.cs", indexedSourceB);
            var generatedPath = CreateDifferentDrivePath(
                root,
                @"packages\generator\Shared.generated.cs");
            var loaded = CreateLoadedWorkspace(
                new WorkspaceProject(
                    projectPathA,
                    "Alpha",
                    "SharedAssembly",
                    [
                        (indexedPathA, "Main.cs", indexedSourceA),
                        (generatedPath, "Shared.generated.cs", generatedSource),
                    ]),
                new WorkspaceProject(
                    projectPathB,
                    "Beta",
                    "SharedAssembly",
                    [
                        (indexedPathB, "Main.cs", indexedSourceB),
                        (generatedPath, "Shared.generated.cs", generatedSource),
                    ]));
            var input = new ResolvedInput(
                InputMode.Project,
                projectPathA,
                root,
                [projectPathA, projectPathB]);
            var options = new IndexOptions { InputPath = projectPathA, ForcedMode = InputMode.Project };
            var coordinator = AnalysisCoordinator.CreateForTesting((_, _, _) => Task.FromResult(loaded));
            var paths = IndexPathResolver.CreateForIndex(
                Path.Combine(root, ".csindex", "index.sqlite"),
                root);

            using var prepared = await coordinator.PrepareAsync(
                input,
                options,
                paths,
                cancellationToken);
            var result = await coordinator.AnalyzeAsync(
                prepared,
                options,
                [],
                [],
                cancellationToken);
            var snapshot = result.Snapshot;

            Assert.Equal(2, snapshot.Projects.Count);
            Assert.Equal(2, snapshot.DocumentsExcluded);
            var endpoints = snapshot.Symbols.Values
                .Where(symbol => symbol.Kind == IndexedSymbolKind.Method && symbol.Name == "Value")
                .ToArray();
            var containingTypes = snapshot.Symbols.Values
                .Where(symbol => symbol.Kind == IndexedSymbolKind.Type && symbol.Name == "Helper")
                .ToArray();
            Assert.Equal(2, endpoints.Length);
            Assert.Equal(2, containingTypes.Length);
            Assert.Equal(2, endpoints.Select(symbol => symbol.StableKey).Distinct(StringComparer.Ordinal).Count());
            Assert.Equal(2, containingTypes.Select(symbol => symbol.StableKey).Distinct(StringComparer.Ordinal).Count());
            Assert.All(endpoints, endpoint =>
            {
                Assert.Null(endpoint.ProjectKey);
                Assert.Null(endpoint.PreferredDeclarationKey);
                Assert.Null(endpoint.SourceDocumentKey);
                Assert.Null(endpoint.SourceStart);
                Assert.Null(endpoint.SourceLength);
                Assert.Contains(endpoint.ContainingSymbolKey!, snapshot.Symbols.Keys);
                Assert.Contains(
                    "|project:",
                    endpoint.StableKey,
                    StringComparison.Ordinal);
            });
            Assert.All(containingTypes, type =>
            {
                Assert.Null(type.ProjectKey);
                Assert.Null(type.PreferredDeclarationKey);
                Assert.Null(type.SourceDocumentKey);
                Assert.Contains("|project:", type.StableKey, StringComparison.Ordinal);
            });
            Assert.All(snapshot.Projects, project =>
            {
                var endpoint = Assert.Single(
                    endpoints,
                    symbol => symbol.StableKey.Contains(
                        $"|project:{project.Key}|",
                        StringComparison.Ordinal));
                var helper = Assert.Single(
                    containingTypes,
                    symbol => symbol.StableKey.Contains(
                        $"|project:{project.Key}|",
                        StringComparison.Ordinal));
                Assert.Equal(helper.StableKey, endpoint.ContainingSymbolKey);

                var caller = Assert.Single(
                    snapshot.Symbols.Values,
                    symbol => symbol.ProjectKey == project.Key && symbol.Name == "Run");
                Assert.Contains(snapshot.Calls, call =>
                    call.CallerSymbolKey == caller.StableKey &&
                    call.CalleeDefinitionKey == endpoint.StableKey);
            });
            Assert.DoesNotContain(
                snapshot.Documents,
                document => document.NormalizedPath.Contains(
                    "Shared.generated.cs",
                    StringComparison.OrdinalIgnoreCase));

            var index = new SqliteIndex(Path.Combine(root, "index.sqlite"));
            await index.SaveAsync(snapshot, cancellationToken);

            var repository = index.CreateQueryRepository();
            var profile = await repository.GetProfileAsync(snapshot.Profile.Name, cancellationToken);
            var storedEndpoints = await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Value",
                typeSimpleName: "Helper",
                kind: IndexedSymbolKind.Method,
                sourceOnly: false,
                cancellationToken: cancellationToken);
            var storedHelpers = await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Helper",
                typeSimpleName: "Helper",
                kind: IndexedSymbolKind.Type,
                sourceOnly: false,
                cancellationToken: cancellationToken);
            Assert.Equal(2, storedEndpoints.Count);
            Assert.Equal(2, storedHelpers.Count);
            Assert.Equal(
                2,
                storedEndpoints.Select(symbol => symbol.StableKey).Distinct(StringComparer.Ordinal).Count());
            Assert.Equal(
                2,
                storedHelpers.Select(symbol => symbol.StableKey).Distinct(StringComparer.Ordinal).Count());
            Assert.All(storedEndpoints, endpoint =>
            {
                Assert.Null(endpoint.PreferredDeclaration);
                Assert.Null(endpoint.DocumentPath);
                Assert.Null(endpoint.PreferredDocumentPath);
                Assert.Null(endpoint.SourceStart);
                Assert.Null(endpoint.SourceLength);
                var snapshotEndpoint = Assert.Single(
                    endpoints,
                    value => value.StableKey == endpoint.StableKey);
                var expectedHelper = Assert.Single(
                    storedHelpers,
                    helper => helper.StableKey == snapshotEndpoint.ContainingSymbolKey);
                Assert.Equal(expectedHelper.Id, endpoint.ContainingSymbolId);
            });
            Assert.Empty(await repository.FindDocumentsAsync(
                profile.Id,
                "Shared.generated.cs",
                cancellationToken));

            foreach (var project in snapshot.Projects)
            {
                var caller = Assert.Single(
                    snapshot.Symbols.Values,
                    symbol => symbol.ProjectKey == project.Key && symbol.Name == "Run");
                var storedCaller = Assert.Single(await repository.FindSymbolCandidatesAsync(
                    profile.Id,
                    name: "Run",
                    typeSimpleName: caller.TypeSimpleName,
                    kind: IndexedSymbolKind.Method,
                    sourceOnly: true,
                    cancellationToken: cancellationToken));
                var expectedEndpoint = Assert.Single(
                    storedEndpoints,
                    endpoint => endpoint.StableKey.Contains(
                        $"|project:{project.Key}|",
                        StringComparison.Ordinal));
                var call = Assert.Single(await repository.GetCallsByCallerAsync(
                    profile.Id,
                    [storedCaller.Id],
                    GeneratedFilter.Include,
                    cancellationToken: cancellationToken));
                Assert.Equal(expectedEndpoint.Id, call.CalleeDefinitionId);
            }
        }
        finally
        {
            DeleteRoot(root);
        }
    }

    [Fact]
    public async Task AnalyzeAndSave_CompilationOnlyDependencyEndpointIsPersistable()
    {
        const string indexedSource = """
            namespace App;
            public sealed class Consumer
            {
                public int Run() => GeneratedApi.Helper.Value();
            }
            """;
        const string generatedSource = """
            // <auto-generated/>
            namespace GeneratedApi;
            public static class Helper
            {
                public static int Value() => Hidden();
                private static int Hidden() => 42;
            }
            """;

        var cancellationToken = TestContext.Current.CancellationToken;
        var root = Path.Combine(
            Path.GetTempPath(),
            "csindex-compilation-only-persistence-tests",
            Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        try
        {
            var projectPath = WriteFile(root, @"Game\Game.csproj", "<Project />");
            var indexedPath = WriteFile(root, @"Game\Main.cs", indexedSource);
            var generatedPath = CreateDifferentDrivePath(
                root,
                @"packages\generator\Helper.generated.cs");
            var loaded = CreateLoadedWorkspace(
                projectPath,
                (indexedPath, "Main.cs", indexedSource),
                (generatedPath, "Helper.cs", generatedSource));
            var input = new ResolvedInput(InputMode.Project, projectPath, root, [projectPath]);
            var options = new IndexOptions { InputPath = projectPath, ForcedMode = InputMode.Project };
            var coordinator = AnalysisCoordinator.CreateForTesting((_, _, _) => Task.FromResult(loaded));
            var paths = IndexPathResolver.CreateForIndex(
                Path.Combine(root, ".csindex", "index.sqlite"),
                root);

            using var prepared = await coordinator.PrepareAsync(
                input,
                options,
                paths,
                cancellationToken);
            var result = await coordinator.AnalyzeAsync(
                prepared,
                options,
                [],
                [],
                cancellationToken);
            var snapshot = result.Snapshot;
            var value = Assert.Single(snapshot.Symbols.Values, symbol => symbol.Name == "Value");
            var helper = Assert.Single(snapshot.Symbols.Values, symbol => symbol.Name == "Helper");
            Assert.Null(value.PreferredDeclarationKey);
            Assert.Null(value.SourceDocumentKey);
            Assert.Equal(1, snapshot.DocumentsExcluded);
            Assert.Single(
                snapshot.Warnings,
                warning => warning.Contains(
                    "Helper.generated.cs",
                    StringComparison.OrdinalIgnoreCase));
            Assert.DoesNotContain(snapshot.Symbols.Values, symbol => symbol.Name == "Hidden");
            Assert.DoesNotContain(snapshot.Documents, document =>
                document.NormalizedPath.Contains("Helper.generated.cs", StringComparison.OrdinalIgnoreCase));
            Assert.DoesNotContain(snapshot.Declarations.Values, declaration =>
                declaration.DocumentKey.Contains("Helper.generated.cs", StringComparison.OrdinalIgnoreCase));
            Assert.DoesNotContain(snapshot.Calls, call => call.CallerSymbolKey == value.StableKey);

            var index = new SqliteIndex(Path.Combine(root, "index.sqlite"));
            await index.SaveAsync(snapshot, cancellationToken);
            Assert.Null(value.ProjectKey);
            Assert.Null(helper.ProjectKey);

            var repository = index.CreateQueryRepository();
            var profile = await repository.GetProfileAsync(snapshot.Profile.Name, cancellationToken);
            var run = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Run",
                typeSimpleName: "Consumer",
                kind: IndexedSymbolKind.Method,
                sourceOnly: true,
                cancellationToken: cancellationToken));
            var storedValue = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Value",
                typeSimpleName: "Helper",
                kind: IndexedSymbolKind.Method,
                sourceOnly: false,
                cancellationToken: cancellationToken));
            Assert.Null(storedValue.PreferredDeclaration);
            Assert.Null(storedValue.DocumentPath);
            Assert.Empty(await repository.FindDocumentsAsync(
                profile.Id,
                "packages/generator/Helper.generated.cs",
                cancellationToken));
            Assert.Empty(await repository.GetCallsByCallerAsync(
                profile.Id,
                [storedValue.Id],
                GeneratedFilter.Include,
                cancellationToken: cancellationToken));

            var calls = await repository.GetCallsByCallerAsync(
                profile.Id,
                [run.Id],
                GeneratedFilter.Include,
                cancellationToken: cancellationToken);
            var call = Assert.Single(calls);
            Assert.Equal(storedValue.Id, call.CalleeDefinitionId);
            Assert.Equal("Main.cs", call.DocumentPath.Split('/').Last());
        }
        finally
        {
            if (Directory.Exists(root))
            {
                Directory.Delete(root, recursive: true);
            }
        }
    }

    [Fact]
    public async Task AnalyzeAndSave_MixedPartialContainingTypeHasConsistentNestedEndpoints()
    {
        const string indexedSource = """
            namespace GeneratedApi;
            public partial class Host
            {
                public int Run() => Nested.Value();
            }
            """;
        const string generatedSource = """
            // <auto-generated/>
            namespace GeneratedApi;
            public partial class Host
            {
                public static class Nested
                {
                    public static partial int Value();
                    public static partial int Value() => 42;
                }
            }
            """;

        var cancellationToken = TestContext.Current.CancellationToken;
        var (root, snapshot) = await AnalyzeSyntheticAsync(
            indexedSource,
            generatedSource,
            @"packages\generator\Host.generated.cs",
            "Host.cs");
        try
        {
            var index = new SqliteIndex(Path.Combine(root, "index.sqlite"));
            await index.SaveAsync(snapshot, cancellationToken);

            var host = Assert.Single(snapshot.Symbols.Values, symbol =>
                symbol.Name == "Host" && symbol.Kind == IndexedSymbolKind.Type);
            var nested = Assert.Single(snapshot.Symbols.Values, symbol =>
                symbol.Name == "Nested" && symbol.Kind == IndexedSymbolKind.Type);
            var value = Assert.Single(snapshot.Symbols.Values, symbol => symbol.Name == "Value");
            Assert.Contains(nested.ContainingSymbolKey!, snapshot.Symbols.Keys);
            Assert.Contains(value.ContainingSymbolKey!, snapshot.Symbols.Keys);
            Assert.Equal(host.StableKey, nested.ContainingSymbolKey);
            Assert.Equal(nested.StableKey, value.ContainingSymbolKey);
            Assert.Null(nested.ProjectKey);
            Assert.Null(value.ProjectKey);
            Assert.Null(value.PreferredDeclarationKey);

            var repository = index.CreateQueryRepository();
            var profile = await repository.GetProfileAsync(snapshot.Profile.Name, cancellationToken);
            var storedHost = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Host",
                typeSimpleName: "Host",
                kind: IndexedSymbolKind.Type,
                sourceOnly: false,
                cancellationToken: cancellationToken));
            var storedNested = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Nested",
                typeSimpleName: "Nested",
                kind: IndexedSymbolKind.Type,
                sourceOnly: false,
                cancellationToken: cancellationToken));
            var storedValue = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Value",
                typeSimpleName: "Nested",
                kind: IndexedSymbolKind.Method,
                sourceOnly: false,
                cancellationToken: cancellationToken));
            Assert.Equal(storedHost.Id, storedNested.ContainingSymbolId);
            Assert.Equal(storedNested.Id, storedValue.ContainingSymbolId);
            Assert.Null(storedValue.PreferredDeclaration);
            var storedRun = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Run",
                typeSimpleName: "Host",
                kind: IndexedSymbolKind.Method,
                sourceOnly: true,
                cancellationToken: cancellationToken));
            var calls = await repository.GetCallsByCallerAsync(
                profile.Id,
                [storedRun.Id],
                GeneratedFilter.Include,
                cancellationToken: cancellationToken);
            Assert.Contains(calls, call => call.CalleeDefinitionId == storedValue.Id);
            Assert.Empty(await repository.FindDocumentsAsync(
                profile.Id,
                "packages/generator/Host.generated.cs",
                cancellationToken));
        }
        finally
        {
            DeleteRoot(root);
        }
    }

    [Fact]
    public async Task AnalyzeAndSave_PartialDefinitionCompilationOnlyKeepsIndexedImplementationIdentity()
    {
        const string indexedSource = """
            namespace App;
            public partial class Consumer
            {
                public int Run() => Partial();
                public partial int Partial() => 42;
            }
            """;
        const string generatedSource = """
            // <auto-generated/>
            namespace App;
            public partial class Consumer
            {
                public partial int Partial();
            }
            """;

        var cancellationToken = TestContext.Current.CancellationToken;
        var (root, snapshot) = await AnalyzeSyntheticAsync(
            indexedSource,
            generatedSource,
            @"packages\generator\Consumer.generated.cs",
            "Consumer.cs");
        try
        {
            var index = new SqliteIndex(Path.Combine(root, "index.sqlite"));
            await index.SaveAsync(snapshot, cancellationToken);

            var partial = Assert.Single(
                snapshot.Symbols.Values,
                symbol => symbol.Name == "Partial" && symbol.ProjectKey is not null);
            Assert.NotNull(partial.PreferredDeclarationKey);
            Assert.Null(partial.SourceDocumentKey);
            Assert.DoesNotContain(
                snapshot.Declarations.Values,
                declaration => declaration.DocumentKey.Contains(
                    "Consumer.generated.cs",
                    StringComparison.OrdinalIgnoreCase));

            var repository = index.CreateQueryRepository();
            var profile = await repository.GetProfileAsync(snapshot.Profile.Name, cancellationToken);
            var storedPartial = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Partial",
                typeSimpleName: "Consumer",
                kind: IndexedSymbolKind.Method,
                sourceOnly: true,
                cancellationToken: cancellationToken));
            var preferredPartial = Assert.Single(await repository.GetPreferredDeclarationsAsync(
                profile.Id,
                [storedPartial.Id],
                includeSourceText: false,
                cancellationToken: cancellationToken));
            Assert.Equal(storedPartial.Id, preferredPartial.SymbolId);
            Assert.Equal(DeclarationRole.Ordinary, preferredPartial.Role);
            Assert.EndsWith(
                "Main.cs",
                preferredPartial.DocumentPath,
                StringComparison.OrdinalIgnoreCase);

            var run = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Run",
                typeSimpleName: "Consumer",
                kind: IndexedSymbolKind.Method,
                sourceOnly: true,
                cancellationToken: cancellationToken));
            var call = Assert.Single(await repository.GetCallsByCallerAsync(
                profile.Id,
                [run.Id],
                GeneratedFilter.Include,
                cancellationToken: cancellationToken));
            Assert.Equal(storedPartial.Id, call.CalleeDefinitionId);
        }
        finally
        {
            DeleteRoot(root);
        }
    }

    [Fact]
    public async Task AnalyzeAndSave_ReducedPartialExtensionDefinitionCompilationOnlyKeepsIndexedImplementationIdentity()
    {
        const string indexedSource = """
            namespace App;
            public static partial class Extensions
            {
                public static partial T Add<T>(this T value) => value;
            }

            public sealed class Consumer
            {
                public int Run() => 1.Add();
            }
            """;
        const string generatedSource = """
            // <auto-generated/>
            namespace App;
            public static partial class Extensions
            {
                public static partial T Add<T>(this T value);
            }
            """;

        var cancellationToken = TestContext.Current.CancellationToken;
        var (root, snapshot) = await AnalyzeSyntheticAsync(
            indexedSource,
            generatedSource,
            @"packages\generator\Extensions.generated.cs",
            "Extensions.cs");
        try
        {
            var index = new SqliteIndex(Path.Combine(root, "index.sqlite"));
            await index.SaveAsync(snapshot, cancellationToken);

            var add = Assert.Single(
                snapshot.Symbols.Values,
                symbol => symbol.Name == "Add" && symbol.ProjectKey is not null);
            Assert.DoesNotContain(snapshot.Symbols.Values, symbol =>
                symbol.Name == "Add" && symbol.ProjectKey is null);
            Assert.NotNull(add.PreferredDeclarationKey);
            Assert.DoesNotContain(
                snapshot.Declarations.Values,
                declaration => declaration.DocumentKey.Contains(
                    "Extensions.generated.cs",
                    StringComparison.OrdinalIgnoreCase));

            var repository = index.CreateQueryRepository();
            var profile = await repository.GetProfileAsync(snapshot.Profile.Name, cancellationToken);
            var storedAdd = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Add",
                typeSimpleName: "Extensions",
                kind: IndexedSymbolKind.Method,
                sourceOnly: true,
                cancellationToken: cancellationToken));
            var preferredAdd = Assert.Single(await repository.GetPreferredDeclarationsAsync(
                profile.Id,
                [storedAdd.Id],
                includeSourceText: false,
                cancellationToken: cancellationToken));
            Assert.Equal(storedAdd.Id, preferredAdd.SymbolId);
            Assert.Equal(DeclarationRole.Ordinary, preferredAdd.Role);
            Assert.EndsWith(
                "Main.cs",
                preferredAdd.DocumentPath,
                StringComparison.OrdinalIgnoreCase);

            var run = Assert.Single(await repository.FindSymbolCandidatesAsync(
                profile.Id,
                name: "Run",
                typeSimpleName: "Consumer",
                kind: IndexedSymbolKind.Method,
                sourceOnly: true,
                cancellationToken: cancellationToken));
            var calls = await repository.GetCallsByCallerAsync(
                profile.Id,
                [run.Id],
                GeneratedFilter.Include,
                cancellationToken: cancellationToken);
            var call = Assert.Single(calls);
            Assert.Equal(ReferenceKind.Invocation, call.ReferenceKind);
            Assert.Equal(storedAdd.Id, call.CalleeDefinitionId);
        }
        finally
        {
            DeleteRoot(root);
        }
    }

    private static async Task<(string Root, IndexSnapshot Snapshot)> AnalyzeSyntheticAsync(
        string indexedSource,
        string generatedSource,
        string generatedRelativePath,
        string generatedName)
    {
        var root = Path.Combine(
            Path.GetTempPath(),
            "csindex-compilation-only-persistence-tests",
            Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        var projectPath = WriteFile(root, @"Game\Game.csproj", "<Project />");
        var indexedPath = WriteFile(root, @"Game\Main.cs", indexedSource);
        var generatedPath = CreateDifferentDrivePath(root, generatedRelativePath);
        var loaded = CreateLoadedWorkspace(
            projectPath,
            (indexedPath, "Main.cs", indexedSource),
            (generatedPath, generatedName, generatedSource));
        var input = new ResolvedInput(InputMode.Project, projectPath, root, [projectPath]);
        var options = new IndexOptions { InputPath = projectPath, ForcedMode = InputMode.Project };
        var coordinator = AnalysisCoordinator.CreateForTesting((_, _, _) => Task.FromResult(loaded));
        var paths = IndexPathResolver.CreateForIndex(
            Path.Combine(root, ".csindex", "index.sqlite"),
            root);

        using var prepared = await coordinator.PrepareAsync(
            input,
            options,
            paths,
            TestContext.Current.CancellationToken);
        var result = await coordinator.AnalyzeAsync(
            prepared,
            options,
            [],
            [],
            TestContext.Current.CancellationToken);
        return (root, result.Snapshot);
    }

    private static string CreateDifferentDrivePath(string referencePath, string relativePath)
    {
        var currentDrive = char.ToUpperInvariant(Path.GetPathRoot(referencePath)![0]);
        var otherDrive = currentDrive == 'Z' ? 'Y' : 'Z';
        return $"{otherDrive}:\\{relativePath}";
    }

    private sealed record WorkspaceProject(
        string ProjectPath,
        string Name,
        string AssemblyName,
        IReadOnlyList<(string Path, string Name, string Source)> Documents);

    private static LoadedWorkspace CreateLoadedWorkspace(
        string projectPath,
        params (string Path, string Name, string Source)[] documents)
        => CreateLoadedWorkspace(
            new WorkspaceProject(projectPath, "TestProject", "TestProject", documents));

    private static LoadedWorkspace CreateLoadedWorkspace(params WorkspaceProject[] projectDefinitions)
    {
        var workspace = new AdhocWorkspace();
        var metadataReferences = GetPlatformReferences();
        var projectIds = new List<ProjectId>();
        var solution = workspace.CurrentSolution;
        foreach (var projectDefinition in projectDefinitions)
        {
            var projectId = ProjectId.CreateNewId();
            projectIds.Add(projectId);
            var projectInfo = ProjectInfo.Create(
                projectId,
                VersionStamp.Create(),
                projectDefinition.Name,
                projectDefinition.AssemblyName,
                LanguageNames.CSharp,
                filePath: projectDefinition.ProjectPath,
                outputFilePath: null,
                compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary),
                parseOptions: new CSharpParseOptions(LanguageVersion.Latest),
                metadataReferences: metadataReferences);
            solution = solution.AddProject(projectInfo);
            foreach (var (path, name, source) in projectDefinition.Documents)
            {
                solution = solution.AddDocument(
                    DocumentInfo.Create(
                        DocumentId.CreateNewId(projectId, name),
                        name,
                        loader: TextLoader.From(
                            TextAndVersion.Create(SourceText.From(source), VersionStamp.Create(), path)),
                        filePath: path));
            }
        }

        Assert.True(workspace.TryApplyChanges(solution));
        var projects = projectIds
            .Select(projectId => workspace.CurrentSolution.GetProject(projectId)!)
            .ToArray();
        return new LoadedWorkspace(
            workspace,
            projects,
            metadataReferences
                .OfType<PortableExecutableReference>()
                .Select(reference => reference.FilePath!)
                .ToArray(),
            [],
            0);
    }

    private static IReadOnlyList<MetadataReference> GetPlatformReferences() =>
        ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))!
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            .Select(path => MetadataReference.CreateFromFile(path))
            .ToArray();

    private static string WriteFile(string root, string relativePath, string contents)
    {
        var path = Path.Combine(root, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, contents);
        return path;
    }

    private static void DeleteRoot(string root)
    {
        if (Directory.Exists(root))
        {
            Directory.Delete(root, recursive: true);
        }
    }
}
