<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CsIndex.Core\CsIndex.Core.csproj" />
    <ProjectReference Include="..\..\src\CsIndex.Storage\CsIndex.Storage.csproj" />
    <ProjectReference Include="..\..\src\CsIndex.Query\CsIndex.Query.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
</Project>
