using CsIndex.Core.Input;
using CsIndex.Core.Model;
using Microsoft.CodeAnalysis.Text;

namespace CsIndex.Core.Analysis;

public static class GeneratedCodeDetector
{
    public static (bool IsGenerated, GenerationKind Kind) Detect(string filePath, SourceText text)
    {
        var fileName = Path.GetFileName(filePath);
        if (fileName.EndsWith(".AssemblyAttributes.cs", StringComparison.OrdinalIgnoreCase))
        {
            return (true, GenerationKind.AssemblyAttributes);
        }

        if (fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
            fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) ||
            fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase))
        {
            return (true, GenerationKind.FileName);
        }

        var parts = Path.GetFullPath(filePath).Split(
            [Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar],
            StringSplitOptions.RemoveEmptyEntries);
        if (parts.Any(part => part.Equals("Generated", StringComparison.OrdinalIgnoreCase) ||
                              part.Equals("GeneratedCode", StringComparison.OrdinalIgnoreCase)))
        {
            return (true, GenerationKind.GeneratedDirectory);
        }

        var prefixLength = Math.Min(2048, text.Length);
        if (prefixLength > 0)
        {
            var prefix = text.ToString(new TextSpan(0, prefixLength));
            if (prefix.Contains("<auto-generated>", StringComparison.OrdinalIgnoreCase) ||
                prefix.Contains("<autogenerated>", StringComparison.OrdinalIgnoreCase))
            {
                return (true, GenerationKind.AutoGeneratedHeader);
            }
        }

        return (false, GenerationKind.None);
    }
}
