namespace CsIndex.Core.Model;

[Flags]
public enum AsyncRole
{
    None = 0,
    DeclaredAsync = 1 << 0,
    ReturnsAwaitable = 1 << 1,
    ContainsAwait = 1 << 2,
    AsyncIterator = 1 << 3,
    ReturnsAsyncEnumerable = 1 << 4,
    AsyncVoid = 1 << 5,
    UniTaskVoid = 1 << 6,
    UsesAwaitForEach = 1 << 7,
    UsesAwaitUsing = 1 << 8,
}

public enum AsyncStatusFilter
{
    All = 0,
    Async = 1,
    Sync = 2,
}

public enum AsyncUsageKind
{
    None = 0,
    Awaited = 1,
    Forwarded = 2,
    Stored = 3,
    Passed = 4,
    Discarded = 5,
    Unobserved = 6,
}

public enum InputMode
{
    Solution = 1,
    Project = 2,
    Directory = 3,
}

public enum GeneratedSourceMode
{
    Physical = 1,
    All = 2,
    None = 3,
}

public enum GenerationKind
{
    None = 0,
    FileName = 1,
    AutoGeneratedHeader = 2,
    GeneratedDirectory = 3,
    AssemblyAttributes = 4,
}

public enum IndexedSymbolKind
{
    Type = 1,
    Method = 2,
    Lambda = 3,
    Initializer = 4,
    TopLevelStatements = 5,
}

public enum DeclarationRole
{
    Ordinary = 1,
    PartialDefinition = 2,
    PartialImplementation = 3,
}

public enum CallablePathSegmentKind
{
    Named = 1,
    Special = 2,
    Lambda = 3,
    AnonymousMethod = 4,
    Initializer = 5,
    TopLevelStatements = 6,
}

public enum IndexedTypeKind
{
    Unknown = 0,
    Array = 1,
    Class = 2,
    Delegate = 3,
    Dynamic = 4,
    Enum = 5,
    Error = 6,
    Interface = 7,
    Module = 8,
    Pointer = 9,
    Struct = 10,
    Structure = 10,
    TypeParameter = 11,
    Submission = 12,
    FunctionPointer = 13,
    Extension = 14,
}

public enum IndexedAccessibility
{
    NotApplicable = 0,
    Private = 1,
    ProtectedAndInternal = 2,
    ProtectedAndFriend = 2,
    Protected = 3,
    Internal = 4,
    Friend = 4,
    ProtectedOrInternal = 5,
    ProtectedOrFriend = 5,
    Public = 6,
}

public enum ReferenceKind
{
    Invocation = 1,
    ObjectCreation = 2,
    MethodGroup = 3,
    DelegateCreation = 4,
    NameOf = 5,
    Operator = 6,
    Conversion = 7,
    DynamicInvocation = 8,
    Unknown = 9,
}

public enum DispatchKind
{
    Static = 1,
    Virtual = 2,
    Interface = 3,
    Dynamic = 4,
}

public enum ResolutionStatus
{
    Resolved = 1,
    Ambiguous = 2,
    Unresolved = 3,
    Dynamic = 4,
}

public enum ResolutionReason
{
    None = 0,
    MissingMetadataReference = 1,
    CompilationError = 2,
    AmbiguousCandidates = 3,
    DynamicDispatch = 4,
    UnsupportedConstruct = 5,
    Unknown = 6,
}

public enum SymbolRelationKind
{
    Inherits = 1,
    Implements = 2,
    Overrides = 3,
    ExplicitlyImplements = 4,
    ImplicitlyImplements = 5,
    PartialDefinition = 6,
    PartialImplementation = 7,
}

public enum CallerScope
{
    Direct = 1,
    Containing = 2,
    Both = 3,
}
