namespace CsIndex.Core.Model;

public enum InputMode
{
    Solution = 1,
    Project = 2,
    Directory = 3,
}

public enum GeneratedSourceMode
{
    Physical = 1,
    All = 2,
    None = 3,
}

public enum GenerationKind
{
    None = 0,
    FileName = 1,
    AutoGeneratedHeader = 2,
    GeneratedDirectory = 3,
    AssemblyAttributes = 4,
}

public enum IndexedSymbolKind
{
    Type = 1,
    Method = 2,
    Lambda = 3,
    Initializer = 4,
    TopLevelStatements = 5,
}

public enum ReferenceKind
{
    Invocation = 1,
    ObjectCreation = 2,
    MethodGroup = 3,
    DelegateCreation = 4,
    NameOf = 5,
    Operator = 6,
    Conversion = 7,
    DynamicInvocation = 8,
    Unknown = 9,
}

public enum DispatchKind
{
    Static = 1,
    Virtual = 2,
    Interface = 3,
    Dynamic = 4,
}

public enum ResolutionStatus
{
    Resolved = 1,
    Ambiguous = 2,
    Unresolved = 3,
    Dynamic = 4,
}

public enum ResolutionReason
{
    None = 0,
    MissingMetadataReference = 1,
    CompilationError = 2,
    AmbiguousCandidates = 3,
    DynamicDispatch = 4,
    UnsupportedConstruct = 5,
    Unknown = 6,
}

public enum SymbolRelationKind
{
    Inherits = 1,
    Implements = 2,
    Overrides = 3,
    ExplicitlyImplements = 4,
    ImplicitlyImplements = 5,
    PartialDefinition = 6,
    PartialImplementation = 7,
}

public enum CallerScope
{
    Direct = 1,
    Containing = 2,
    Both = 3,
}
