using System.Collections.Immutable;
using CsIndex.Core.Analysis;
using CsIndex.Core.Caching;
using CsIndex.Core.Input;
using CsIndex.Core.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace CsIndex.Core.Tests;

public sealed class CompilationOnlyGeneratedDocumentTests
{
    [Theory]
    [InlineData(InputMode.Solution)]
    [InlineData(InputMode.Project)]
    public async Task Prepare_CrossVolumeGeneratedDocumentIsCompilationOnlyForEveryMsBuildMode(InputMode mode)
    {
        using var temporary = new TempDirectory();
        var projectPath = temporary.Write("Game/Game.csproj", "<Project />");
        var indexedPath = temporary.Write(
            "Game/Main.cs",
            "namespace App; public sealed class Main { }");
        var generatedPath = CreateDifferentDrivePath(
            temporary.Path,
            @"packages\runner\DefaultRunnerReporters.cs");
        const string generatedSource =
            "// <auto-generated>\nnamespace Runner; public sealed class Reporter { }";
        var loaded = CreateLoadedWorkspace(
            projectPath,
            (indexedPath, "Main.cs", File.ReadAllText(indexedPath)),
            (generatedPath, "DefaultRunnerReporters.cs", generatedSource));
        var input = new ResolvedInput(mode, projectPath, temporary.Path, [projectPath]);
        var options = new IndexOptions { InputPath = projectPath, ForcedMode = mode };
        var paths = CreateStandardPaths(temporary.Path);
        var coordinator = AnalysisCoordinator.CreateForTesting((_, _, _) => Task.FromResult(loaded));

        using var prepared = await coordinator.PrepareAsync(
            input,
            options,
            paths,
            TestContext.Current.CancellationToken);

        var generatedDocument = Assert.Single(
            prepared.Projects.Single().Documents,
            document => document.FilePath == generatedPath);
        Assert.True(prepared.DocumentSelection.IsCompilationOnly(generatedDocument));
        Assert.Equal(1, prepared.DocumentsExcluded);
        var warning = Assert.Single(
            prepared.Warnings,
            value => value.Contains(generatedPath, StringComparison.OrdinalIgnoreCase));
        Assert.Contains("kept in the compilation", warning, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("excluded from the portable index", warning, StringComparison.OrdinalIgnoreCase);
        Assert.Throws<InputResolutionException>(() => prepared.Mappings.GetDocumentPath(generatedDocument));
    }

    [Theory]
    [InlineData(GenerationKind.FileName, @"packages\runner\Reporter.g.cs")]
    [InlineData(GenerationKind.GeneratedDirectory, @"packages\Generated\Reporter.cs")]
    [InlineData(GenerationKind.AssemblyAttributes, @"obj\Debug\net10.0\Runner.AssemblyAttributes.cs")]
    public async Task Prepare_CrossVolumeGeneratedDocumentClassifiesByEstablishedGenerationKind(
        GenerationKind expectedKind,
        string relativePath)
    {
        using var temporary = new TempDirectory();
        var projectPath = temporary.Write("Game/Game.csproj", "<Project />");
        var generatedPath = CreateDifferentDrivePath(temporary.Path, relativePath);
        const string source = "namespace Generated; public sealed class Reporter { }";
        var loaded = CreateLoadedWorkspace(
            projectPath,
            (generatedPath, Path.GetFileName(generatedPath), source));
        var input = new ResolvedInput(InputMode.Project, projectPath, temporary.Path, [projectPath]);
        var options = new IndexOptions { InputPath = projectPath, ForcedMode = InputMode.Project };
        var coordinator = AnalysisCoordinator.CreateForTesting((_, _, _) => Task.FromResult(loaded));

        using var prepared = await coordinator.PrepareAsync(
            input,
            options,
            CreateStandardPaths(temporary.Path),
            TestContext.Current.CancellationToken);

        var generatedDocument = Assert.Single(prepared.Projects.Single().Documents);
        Assert.True(prepared.DocumentSelection.IsCompilationOnly(generatedDocument));
        var compilationOnly = Assert.Single(
            prepared.DocumentSelection.GetCompilationOnly(prepared.Projects.Single()));
        Assert.Equal(expectedKind, compilationOnly.GenerationKind);
        Assert.Equal(HashUtilities.Sha256(source), compilationOnly.ContentHash.ToArray());
    }

    [Fact]
    public async Task Prepare_SameVolumeGeneratedDocumentRemainsMappedAndIndexed()
    {
        using var temporary = new TempDirectory();
        var projectPath = temporary.Write("Game/Game.csproj", "<Project />");
        var generatedPath = temporary.Write(
            "Game/Bindings.g.cs",
            "namespace Generated; public sealed class Bindings { }");
        var loaded = CreateLoadedWorkspace(
            projectPath,
            (generatedPath, "Bindings.g.cs", File.ReadAllText(generatedPath)));
        var input = new ResolvedInput(InputMode.Project, projectPath, temporary.Path, [projectPath]);
        var options = new IndexOptions { InputPath = projectPath, ForcedMode = InputMode.Project };
        var coordinator = AnalysisCoordinator.CreateForTesting((_, _, _) => Task.FromResult(loaded));

        using var prepared = await coordinator.PrepareAsync(
            input,
            options,
            CreateStandardPaths(temporary.Path),
            TestContext.Current.CancellationToken);

        var generatedDocument = Assert.Single(prepared.Projects.Single().Documents);
        Assert.True(prepared.DocumentSelection.IsIndexable(generatedDocument));
        Assert.False(prepared.DocumentSelection.IsCompilationOnly(generatedDocument));
        Assert.Equal("Game/Bindings.g.cs", prepared.Mappings.GetDocumentPath(generatedDocument));

        var result = await coordinator.AnalyzeAsync(
            prepared,
            options,
            [],
            [],
            TestContext.Current.CancellationToken);
        var document = Assert.Single(result.Snapshot.Documents);
        Assert.Equal("Game/Bindings.g.cs", document.NormalizedPath);
        Assert.True(document.IsGenerated);
    }

    [Fact]
    public async Task Analyze_UsesCompilationOnlyDeclarationForBindingButDoesNotIndexItsSourceOrBody()
    {
        const string indexedSource = """
            namespace App;
            public sealed class Consumer
            {
                public int Run() => GeneratedApi.Helper.Value();
            }
            """;
        const string generatedSource = """
            // <auto-generated/>
            namespace GeneratedApi;
            public static class Helper
            {
                public static int Value() => Hidden();
                private static int Hidden() => 42;
            }
            """;

        var snapshot = await AnalyzeWithCompilationOnlyDocumentAsync(
            indexedSource,
            generatedSource,
            @"packages\generator\Helper.generated.cs");

        var consumer = Assert.Single(snapshot.Symbols.Values, symbol => symbol.Name == "Run");
        var value = Assert.Single(snapshot.Symbols.Values, symbol => symbol.Name == "Value");
        var helper = Assert.Single(snapshot.Symbols.Values, symbol => symbol.Name == "Helper");
        Assert.NotNull(consumer.PreferredDeclarationKey);
        Assert.Null(value.ProjectKey);
        Assert.Null(value.PreferredDeclarationKey);
        Assert.Null(value.SourceDocumentKey);
        Assert.Null(helper.ProjectKey);
        Assert.DoesNotContain(snapshot.Symbols.Values, symbol => symbol.Name == "Hidden");
        Assert.Contains(snapshot.Calls, call =>
            call.CallerSymbolKey == consumer.StableKey && call.CalleeDefinitionKey == value.StableKey);
        Assert.DoesNotContain(snapshot.Calls, call => call.CallerSymbolKey == value.StableKey);
        Assert.Single(snapshot.Documents);
        Assert.Equal(1, snapshot.DocumentsExcluded);
        Assert.Single(
            snapshot.Warnings,
            warning => warning.Contains("Helper.generated.cs", StringComparison.OrdinalIgnoreCase));
        Assert.All(snapshot.Declarations.Values, declaration =>
            Assert.DoesNotContain("Helper.generated.cs", declaration.DocumentKey, StringComparison.OrdinalIgnoreCase));
    }

    [Fact]
    public async Task ProjectFingerprint_CompilationOnlyDocumentsArePortableContentSensitiveKindSensitiveAndDeterministic()
    {
        const string indexedSource = "namespace App; public sealed class Consumer { }";
        const string generatedSource = """
            // <auto-generated/>
            namespace GeneratedApi;
            public static class Helper { public static int Value() => 42; }
            """;
        const string changedGeneratedSource = """
            // <auto-generated/>
            namespace GeneratedApi;
            public static class Helper { public static int Value() => 43; }
            """;

        var firstRelocatedFingerprint = await AnalyzeProjectFingerprintAsync(
            'Y',
            @"packages\generator\Helper.generated.cs",
            "Helper.cs",
            indexedSource,
            generatedSource);
        var secondRelocatedFingerprint = await AnalyzeProjectFingerprintAsync(
            'Z',
            @"packages\generator\Helper.generated.cs",
            "Helper.cs",
            indexedSource,
            generatedSource);
        var changedContentFingerprint = await AnalyzeProjectFingerprintAsync(
            'Y',
            @"packages\generator\Helper.generated.cs",
            "Helper.cs",
            indexedSource,
            changedGeneratedSource);
        var changedDocumentNameFingerprint = await AnalyzeProjectFingerprintAsync(
            'Y',
            @"packages\generator\Helper.generated.cs",
            "RenamedHelper.cs",
            indexedSource,
            generatedSource);
        var fileNameGenerationFingerprint = await AnalyzeProjectFingerprintAsync(
            'Y',
            @"packages\generator\Helper.generated.cs",
            "Helper.cs",
            indexedSource,
            generatedSource);
        var generatedDirectoryFingerprint = await AnalyzeProjectFingerprintAsync(
            'Y',
            @"packages\Generated\Helper.cs",
            "Helper.cs",
            indexedSource,
            generatedSource);

        Assert.Equal(firstRelocatedFingerprint, secondRelocatedFingerprint);
        Assert.NotEqual(firstRelocatedFingerprint, changedContentFingerprint);
        Assert.NotEqual(firstRelocatedFingerprint, changedDocumentNameFingerprint);
        Assert.NotEqual(fileNameGenerationFingerprint, generatedDirectoryFingerprint);

        var repeated = await AnalyzeProjectFingerprintTwiceAsync(
            'Y',
            @"packages\generator\Helper.generated.cs",
            "Helper.cs",
            indexedSource,
            generatedSource);
        Assert.Equal(repeated.First, repeated.Second);
    }

    [Fact]
    public async Task Prepare_CancellationAfterDocumentClassificationDisposesWorkspace()
    {
        using var temporary = new TempDirectory();
        var projectPath = temporary.Write("Game/Game.csproj", "<Project />");
        var firstPath = CreateDifferentDrivePath(temporary.Path, @"packages\runner\First.g.cs");
        var secondPath = CreateDifferentDrivePath(temporary.Path, @"packages\runner\Second.g.cs");
        var loaded = CreateLoadedWorkspace(
            projectPath,
            (firstPath, "First.g.cs", "namespace Generated; public sealed class First { }"),
            (secondPath, "Second.g.cs", "namespace Generated; public sealed class Second { }"));
        var input = new ResolvedInput(InputMode.Project, projectPath, temporary.Path, [projectPath]);
        var options = new IndexOptions { InputPath = projectPath, ForcedMode = InputMode.Project };
        var coordinator = AnalysisCoordinator.CreateForTesting((_, _, _) => Task.FromResult(loaded));
        using var cancellation = new CancellationTokenSource();
        var classificationItems = 0;
        coordinator.AfterDocumentClassificationItem = () =>
        {
            classificationItems++;
            cancellation.Cancel();
        };

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => coordinator.PrepareAsync(
            input,
            options,
            CreateStandardPaths(temporary.Path),
            cancellation.Token));

        Assert.Equal(1, classificationItems);
        Assert.True(loaded.IsDisposed);
    }

    private static IndexPathResolver CreateStandardPaths(string storageRoot) =>
        IndexPathResolver.CreateForIndex(
            Path.Combine(storageRoot, ".csindex", "index.sqlite"),
            storageRoot);

    private static string CreateDifferentDrivePath(string referencePath, string relativePath)
    {
        var currentDrive = char.ToUpperInvariant(Path.GetPathRoot(referencePath)![0]);
        var otherDrive = currentDrive == 'Z' ? 'Y' : 'Z';
        return $"{otherDrive}:\\{relativePath}";
    }

    private static async Task<IndexSnapshot> AnalyzeWithCompilationOnlyDocumentAsync(
        string indexedSource,
        string generatedSource,
        string generatedRelativePath)
    {
        using var temporary = new TempDirectory();
        var projectPath = temporary.Write("Game/Game.csproj", "<Project />");
        var indexedPath = temporary.Write("Game/Main.cs", indexedSource);
        var generatedPath = CreateDifferentDrivePath(temporary.Path, generatedRelativePath);
        var loaded = CreateLoadedWorkspace(
            projectPath,
            (indexedPath, "Main.cs", indexedSource),
            (generatedPath, Path.GetFileName(generatedRelativePath), generatedSource));
        var input = new ResolvedInput(InputMode.Project, projectPath, temporary.Path, [projectPath]);
        var options = new IndexOptions { InputPath = projectPath, ForcedMode = InputMode.Project };
        var coordinator = AnalysisCoordinator.CreateForTesting((_, _, _) => Task.FromResult(loaded));

        using var prepared = await coordinator.PrepareAsync(
            input,
            options,
            CreateStandardPaths(temporary.Path),
            TestContext.Current.CancellationToken);
        return (await coordinator.AnalyzeAsync(
            prepared,
            options,
            [],
            [],
            TestContext.Current.CancellationToken)).Snapshot;
    }

    private static async Task<byte[]> AnalyzeProjectFingerprintAsync(
        char externalDrive,
        string generatedRelativePath,
        string generatedName,
        string indexedSource,
        string generatedSource)
    {
        var (first, _) = await AnalyzeProjectFingerprintTwiceAsync(
            externalDrive,
            generatedRelativePath,
            generatedName,
            indexedSource,
            generatedSource,
            analyzeTwice: false);
        return first;
    }

    private static async Task<(byte[] First, byte[] Second)> AnalyzeProjectFingerprintTwiceAsync(
        char externalDrive,
        string generatedRelativePath,
        string generatedName,
        string indexedSource,
        string generatedSource,
        bool analyzeTwice = true)
    {
        using var temporary = new TempDirectory();
        var projectPath = temporary.Write("Game/Game.csproj", "<Project />");
        var indexedPath = temporary.Write("Game/Main.cs", indexedSource);
        var generatedPath = $"{externalDrive}:\\{generatedRelativePath}";
        var loaded = CreateLoadedWorkspace(
            projectPath,
            (indexedPath, "Main.cs", indexedSource),
            (generatedPath, generatedName, generatedSource));
        var input = new ResolvedInput(InputMode.Project, projectPath, temporary.Path, [projectPath]);
        var options = new IndexOptions { InputPath = projectPath, ForcedMode = InputMode.Project };
        var coordinator = AnalysisCoordinator.CreateForTesting((_, _, _) => Task.FromResult(loaded));

        using var prepared = await coordinator.PrepareAsync(
            input,
            options,
            CreateStandardPaths(temporary.Path),
            TestContext.Current.CancellationToken);
        var firstResult = await coordinator.AnalyzeAsync(
            prepared,
            options,
            [],
            [],
            TestContext.Current.CancellationToken);
        if (!analyzeTwice)
        {
            var fingerprint = firstResult.Snapshot.Projects.Single().Fingerprint;
            return (fingerprint, fingerprint);
        }

        var secondResult = await coordinator.AnalyzeAsync(
            prepared,
            options,
            [],
            [],
            TestContext.Current.CancellationToken);
        return (
            firstResult.Snapshot.Projects.Single().Fingerprint,
            secondResult.Snapshot.Projects.Single().Fingerprint);
    }

    private static LoadedWorkspace CreateLoadedWorkspace(
        string? projectPath,
        params (string Path, string Name, string Source)[] documents)
    {
        var workspace = new AdhocWorkspace();
        var projectId = ProjectId.CreateNewId();
        var metadataReferences = GetPlatformReferences();
        var projectInfo = ProjectInfo.Create(
            projectId,
            VersionStamp.Create(),
            "TestProject",
            "TestProject",
            LanguageNames.CSharp,
            filePath: projectPath,
            outputFilePath: null,
            compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary),
            parseOptions: new CSharpParseOptions(LanguageVersion.Latest),
            metadataReferences: metadataReferences);
        var solution = workspace.CurrentSolution.AddProject(projectInfo);
        foreach (var (path, name, source) in documents)
        {
            solution = solution.AddDocument(
                DocumentInfo.Create(
                    DocumentId.CreateNewId(projectId, name),
                    name,
                    loader: TextLoader.From(
                        TextAndVersion.Create(SourceText.From(source), VersionStamp.Create(), path)),
                    filePath: path));
        }

        Assert.True(workspace.TryApplyChanges(solution));
        return CreateLoadedWorkspace(workspace, projectId, metadataReferences);
    }

    private static LoadedWorkspace CreateLoadedWorkspace(
        AdhocWorkspace workspace,
        ProjectId projectId,
        IReadOnlyList<MetadataReference> metadataReferences)
    {
        var project = workspace.CurrentSolution.GetProject(projectId)!;
        return new LoadedWorkspace(
            workspace,
            [project],
            metadataReferences
                .OfType<PortableExecutableReference>()
                .Select(reference => reference.FilePath!)
                .ToArray(),
            [],
            0);
    }

    private static IReadOnlyList<MetadataReference> GetPlatformReferences() =>
        ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))!
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            .Select(path => MetadataReference.CreateFromFile(path))
            .ToArray();

}
